# Generated by Django 6.0.4 on 2026-04-26 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=255)),
                ('course_level', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('Other', 'Other')], max_length=10)),
                ('mode_of_teaching', models.CharField(choices=[('Lecture', 'Lecture'), ('Practical', 'Practical'), ('Tutorial', 'Tutorial')], max_length=20)),
                ('classes_assigned', models.IntegerField()),
                ('classes_taught', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
