# Generated by Django 6.0.4 on 2026-04-26 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSupportEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('activity_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_audience', models.CharField(max_length=255)),
                ('hours_spent', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_support_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
