# Generated by Django 6.0.4 on 2026-04-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbas', '0002_studentsupportentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsupportentry',
            name='supporting_image',
            field=models.ImageField(blank=True, null=True, upload_to='pbas/student_support/'),
        ),
    ]
