# Generated by Django 6.0.4 on 2026-04-26 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbas', '0003_studentsupportentry_supporting_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('research_type', models.CharField(choices=[('Journal', 'Journal Publication'), ('Conference', 'Conference Paper'), ('Project', 'Research Project'), ('Guidance', 'Research Guidance (PhD/MPhil)'), ('Patent', 'Patent/Copyright'), ('Book', 'Book/Book Chapter')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('journal_or_funding', models.CharField(help_text='Journal name or Funding agency', max_length=500)),
                ('status_or_impact', models.CharField(help_text='Impact Factor, Status (Ongoing/Completed), etc.', max_length=100)),
                ('supporting_image', models.ImageField(blank=True, null=True, upload_to='pbas/research/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
