# Generated by Django 6.0.4 on 2026-04-26 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbas', '0004_researchentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('contribution_type', models.CharField(choices=[('Invited Lecture', 'Invited Lecture'), ('Resource Person', 'Resource Person'), ('Paper Presentation', 'Paper Presentation'), ('Award/Fellowship', 'Award/Fellowship'), ('Policy Document', 'Policy Document'), ('Other', 'Other Academic Achievement')], max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('event_name', models.CharField(max_length=500)),
                ('organization', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('supporting_image', models.ImageField(blank=True, null=True, upload_to='pbas/academic/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_contributions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
