# Generated by Django 6.0.4 on 2026-04-26 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbas', '0005_academiccontribution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionalResponsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('responsibility_type', models.CharField(choices=[('Administrative', 'Administrative (IQAC/HOD/Dean)'), ('Committee', 'Committee Member/Coordinator'), ('Examination', 'Examination/Evaluation Duty'), ('Admission', 'Admission Related'), ('Student Welfare', 'Student Welfare/Co-curricular'), ('Other', 'Other Institutional Duty')], max_length=50)),
                ('position', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('supporting_image', models.ImageField(blank=True, null=True, upload_to='pbas/institutional/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutional_responsibilities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
