# Generated by Django 6.0.4 on 2026-04-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbas', '0006_institutionalresponsibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiccontribution',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academiccontribution',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionalresponsibility',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionalresponsibility',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchentry',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchentry',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsupportentry',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsupportentry',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachingentry',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachingentry',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
