# Generated by Django 6.0.4 on 2026-04-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbas', '0007_academiccontribution_from_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiccontribution',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchentry',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachingentry',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
