# Generated by Django 6.0.4 on 2026-10-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbas', '0008_academiccontribution_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingentry',
            name='supporting_image',
            field=models.ImageField(blank=True, null=True, upload_to='pbas/teaching/'),
        ),
    ]
