# Generated by Django 6.0.4 on 2026-10-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbas', '0009_teachingentry_supporting_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiccontribution',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='institutionalresponsibility',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='researchentry',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='studentsupportentry',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teachingentry',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
