# Generated by Django 6.0.4 on 2026-10-05 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbas', '0010_academiccontribution_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('activity_type', models.CharField(max_length=100, unique=True)),
                ('points_per_unit', models.FloatField(default=10.0)),
                ('is_per_hour', models.BooleanField(default=False)),
                ('max_capped_points', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('activity_id', models.IntegerField(blank=True, null=True)),
                ('activity_title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='pbas/evidence/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('Certificate', 'Certificate'), ('Publication', 'Publication (PDF)'), ('Appointment Letter', 'Appointment Letter'), ('Attendance/Log', 'Attendance / Logbook'), ('Other', 'Other Evidence')], default='Certificate', max_length=50)),
                ('status', models.CharField(default='Verified', max_length=20)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppraisalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('title', models.CharField(default='Annual Appraisal', max_length=255)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('target_score', models.FloatField(default=300.0)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Under Review', 'Under Review'), ('Submitted', 'Submitted'), ('Completed', 'Completed')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisal_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'academic_year')},
            },
        ),
    ]
