# Generated by Django 6.0.4 on 2026-10-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbas', '0011_scoringrule_activityevidence_appraisalperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiccontribution',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted')], default='Draft', max_length=20),
        ),
        migrations.AddField(
            model_name='institutionalresponsibility',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted')], default='Draft', max_length=20),
        ),
        migrations.AddField(
            model_name='researchentry',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted')], default='Draft', max_length=20),
        ),
        migrations.AddField(
            model_name='studentsupportentry',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted')], default='Draft', max_length=20),
        ),
        migrations.AddField(
            model_name='teachingentry',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted')], default='Draft', max_length=20),
        ),
    ]
