# Generated by Django 6.0.4 on 2026-10-06 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbas', '0012_academiccontribution_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academiccontribution',
            name='status',
        ),
        migrations.RemoveField(
            model_name='institutionalresponsibility',
            name='status',
        ),
        migrations.RemoveField(
            model_name='researchentry',
            name='status',
        ),
        migrations.RemoveField(
            model_name='studentsupportentry',
            name='status',
        ),
        migrations.RemoveField(
            model_name='teachingentry',
            name='status',
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('Deadline', 'Appraisal Deadline'), ('Evidence', 'Incomplete Evidence'), ('Goal', 'Goal Progress'), ('General', 'General Notification')], default='General', max_length=20)),
                ('icon', models.CharField(default='🔔', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('action_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
