# Generated by Django 6.0.4 on 2026-10-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, default='Assistant Professor', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='orcid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='qualification',
            field=models.CharField(blank=True, default='Ph.D.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='research_interests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
