# Generated by Django 6.0.4 on 2026-10-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_designation_user_orcid_user_qualification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='qualification',
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='orcid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
